### ISSUE TITLE
Layoutコンポーネントを作成する

### ISSUE THREAD

**Issue by yoko-at-home** [tocchi-739/qin-team-dev#1]
- Layoutコンポーネントを作成し
- 各ページごとにインポートしているHeader/FooterをLayoutコンポーネントにインポート
- 各ページではLayoutコンポーネントで囲むことでレイアウトが完成させる
- レイアウトに関するコードは一つのディレクトリにまとめる

**Comment by tocchi-739** [comment]
https://github.com/tocchi-739/qin-team-dev/pull/4
