### ISSUE TITLE
ボタンコンポーネントのリンク修正

### ISSUE THREAD

**Issue by perusonaryu** [tocchi-739/qin-team-dev#3]
下記ディレクトリの27,35行目のボタンコンポーネントに直接URLを指定しているため画面遷移時にローディングが入り、SPAになっていない。
> qin-team-dev/src/pages/index.jsx 

下記を参考に修正するといいと思います。
https://mantine.dev/guides/next
![スクリーンショット 2022-08-16 22 29 31](https://user-images.githubusercontent.com/64568710/184891619-0d893a3c-ac35-4da0-b44b-98aaa8c2b7eb.png)
![スクリーンショット 2022-08-16 22 29 42](https://user-images.githubusercontent.com/64568710/184891665-b7a2914f-dd2e-4db3-947c-7931281cc84c.png)
/

**Comment by tocchi-739** [comment]
プルリクのタイトルおかしいですが、ここでボタンコンポーネントのリンク修正もしています！
https://github.com/tocchi-739/qin-team-dev/pull/5
